### ISSUE TITLE
LIQO Home View

### ISSUE THREAD

**Issue by nappozord** [liqotech/dashboard#19]
## Description
This issue tracks the addition of an home view of LIQO to the dashboard, which purpose is to monitor and manage LIQO, the connection between clusters, have a look at the available and the connected peers and control the status of the connections as well as the overall status of the home cluster and a general overview of the consumed resources.
## PRs
- [x] Init Home View (ref. #18)
  - Creation and design of the home view
  - Header of the view, which will show if LIQO is running and the available modes
- [x] Connected peers (ref. #20)
  - List of peers connected to your cluster, each one designed to show the direction of the connection and the general consumption of the cluster
  - Possibility to disconnect from a peer
- [x] Available peers (ref. #22) 
  - List of peers available for connection, showing the type of connection (LAN or WAN) and the status of the connection (connecting or possible errors) 
  - Possibility to connect to a peer
  - Possibility to manually add a peer
- [x] Property view for connected and available peers (ref. #24)
  - Shows all the properties and associated resources of the foreign cluster
- [x] Detail view for connected peers (ref. #25)
  - Shows all the detail of the connection
  - List of used resources (CPU, RAM) 
  - List of pods offloaded from and to a foreign cluster
- [x] General status of the Home (your) cluster and the Foreign (every other) clusters (ref. #26)
  - General usage of the home cluster's resources (CPU, RAM)
  - General usage of foreign clusters' resources (CPU, RAM)
- [x] Functions to show actual (and real-time) resource consumption of pods per connection (ref. #28)
- [x] Update pods automatically every 30 seconds (ref. #31)
